export const SSM_DOCUMENT_TYPES = [
    "IPSSM",
    "RISK_ASSESSMENT",
    "PPP",
    "THEMATIC",
    "DECISION",
    "PSI",
    "REGISTER",
    "EXPOSURE_SHEET",
    "SSM_CONVENTION",
    "DANGEROUS_SUBSTANCES",
    "EMERGENCY_PROCEDURE",
    "OTHER"
];
export const SSM_DOCUMENT_TARGET_TYPES = [
    "JOB_POSITION",
    "DEPARTMENT",
    "WORKSITE",
    "ENTITY",
    "ALL"
];
