export const HELPDESK_TICKET_STATUSES = [
    "OPEN",
    "WAITING_OPERATOR",
    "WAITING_USER",
    "WAITING_INFO",
    "CLOSED"
];
export const HELPDESK_TICKET_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"];
export const HELPDESK_TICKET_SOURCES = ["PORTAL", "SURVEY", "CHATBOT", "EMAIL", "MANUAL"];
